//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TcpCommSvr.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TCPCOMMSVR_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDD_DLG_PARA                    129
#define IDD_DLG_READER_QRY              130
#define IDD_DLG_CARD_QRY                131
#define IDD_DLG_DISPLAY                 132
#define IDB_BITMAP1                     139
#define IDD_DLG_DISPLAY_TBL             140
#define IDD_DLG_LOGIN                   141
#define IDD_DLG_PARA_MNG                142
#define IDD_DLG_USER_MNG                143
#define IDD_DLG_ZONE_MNG                144
#define IDD_DLG_DEV_MNG                 145
#define IDD_DLG_CARD_MNG                146
#define IDD_DLG_TBL_MNG                 147
#define IDD_DLG_NEW_DATA_QRY            148
#define IDC_LIST1                       1000
#define IDC_LIST2                       1001
#define IDC_BTN_PARA                    1002
#define IDC_BTN_READER_QRY              1003
#define IDC_BTN_CARD_QRY                1004
#define IDC_CHECK1                      1005
#define IDC_BTN_START                   1006
#define IDC_BTN_STOP                    1007
#define IDC_STATIC_CONN_NUM             1009
#define IDC_EDIT1                       1010
#define IDC_EDIT2                       1011
#define IDC_COMBO1                      1012
#define IDC_COMBO2                      1013
#define IDC_BTN_SEND                    1017
#define IDC_EDIT_CMD                    1018
#define IDC_STATIC_IN_OUT_SIZE          1019
#define IDC_BTN_SAVE_ONE                1020
#define IDC_BTN_SEND_ONE                1021
#define IDC_COMBO3                      1022
#define IDC_LOAD_DOC                    1023
#define IDC_BTN_SAVE_ALL                1024
#define IDC_BTN_SEND_ALL                1025
#define IDC_STATIC_Q_COUNT              1026
#define IDC_BTN_TMD_START               1027
#define IDC_STATIC_MAP                  1028
#define IDC_STATIC_TIME                 1029
#define IDC_STATIC_LOGO                 1030
#define IDC_LIST_CARD_INFO              1031
#define IDC_STATIC_DEMO                 1032
#define IDC_STATIC_A                    1033
#define IDC_STATIC_B                    1034
#define IDC_STATIC_C                    1035
#define IDC_STATIC_1                    1036
#define IDC_STATIC_2                    1037
#define IDC_STATIC_3                    1038
#define IDC_STATIC_4                    1039
#define IDC_STATIC_5                    1040
#define IDC_STATIC_6                    1041
#define IDC_STATIC_7                    1042
#define IDC_STATIC_8                    1043
#define IDC_STATIC_9                    1044
#define IDC_LIST_CARD_INFO_X            1045
#define IDC_STATIC_MAP_X                1046
#define IDC_STATIC_MAP_A                1047
#define IDC_STATIC_MAP_B                1048
#define IDC_STATIC_TITLE                1049
#define IDC_STATIC_TITLE_A              1050
#define IDC_STATIC_TITLE_B              1051
#define IDC_STATIC_TITLE_C              1052
#define IDC_STATIC_TOT_1                1053
#define IDC_STATIC_TOT_2                1054
#define IDC_STATIC_TOT_3                1055
#define IDC_STATIC_TOT_4                1056
#define IDC_STATIC_TOT_A                1057
#define IDC_STATIC_TOT_B                1058
#define IDC_STATIC_TITLE_M4_1           1059
#define IDC_STATIC_TITLE_M4_2           1060
#define IDC_STATIC_CONTENT_M4_1         1061
#define IDC_STATIC_CONTENT_M4_2         1062
#define IDC_STATIC_TAIL_M4_1            1063
#define IDC_STATIC_LOGO_M4_1            1064
#define IDC_STATIC_LOGIN_LOGO           1065
#define IDC_EDIT_USER                   1066
#define IDC_EDIT_PASSWORD               1067
#define IDC_BTN_PARA_MNG                1068
#define IDC_TREE_PARA                   1070
#define IDC_STATIC_USER_MNG             1071
#define IDC_LIST_CARD                   1072
#define IDC_EDIT3                       1073
#define IDC_EDIT4                       1074
#define IDC_EDIT5                       1075
#define IDC_EDIT6                       1076
#define IDC_BTN_CARD_ADD                1077
#define IDC_BTN_CARD_DEL                1078
#define IDC_BTN_CARD_UPD                1079
#define IDC_TAB1                        1080
#define IDC_BUTTON1                     1081
#define IDC_BTN_DEV_DEL                 1082
#define IDC_BTN_DEV_UPD                 1083
#define IDC_BTN_DEV_ADD                 1084
#define IDC_EDIT_DEV_NO                 1085
#define IDC_EDIT_DEV_ZONE_NO            1086
#define IDC_EDIT_DEV_ZONE_NAME          1087
#define IDC_LIST_DEV                    1088
#define IDC_RADIO_LEFT                  1089
#define IDC_RADIO_RIGHT                 1090
#define IDC_BTN_ZONE_UPD                1092
#define IDC_LIST_ZONE                   1093
#define IDC_EDIT_ZONE_NO                1094
#define IDC_EDIT_ZONE_NAME              1095
#define IDC_BTN_ZONE_SAVE               1096
#define IDC_BTN_USER_DEL                1097
#define IDC_BTN_USER_UPD                1098
#define IDC_LIST_USER                   1099
#define IDC_EDIT_USER_NAME              1100
#define IDC_EDIT_PSW                    1101
#define IDC_COMBO_GRADE                 1102
#define IDC_BTN_USER_ADD                1103
#define IDC_CHECK_TBL1                  1104
#define IDC_CHECK_TBL2                  1105
#define IDC_CHECK_TBL3                  1106
#define IDC_CHECK_TBL4                  1107
#define IDC_CHECK_TBL5                  1108
#define IDC_CHECK_TBL6                  1109
#define IDC_LIST_TBL1                   1110
#define IDC_BTN_TBL_SAVE                1111
#define IDC_STATIC_LOGIN_INFO           1112
#define IDC_BTN_INFO_QRY                1113
#define IDC_BTN_ROOM_QRY_NEW            1114
#define IDC_LIST_POINT_INFO_NEW         1115
#define IDC_BTN_POINT_QRY_NEW           1116
#define IDC_CMB_CARD_NO_NEW             1117
#define IDC_BTN_CARD_QRY_NEW            1118
#define IDC_CMB_ROOM_NO_NEW             1119
#define IDC_CMB_POINT_NO_NEW            1120
#define IDC_LIST_CARD_INFO_NEW          1121
#define IDC_LIST_ROOM_INFO_NEW          1122
#define IDC_BTN_STOP_CONNECT            1123
#define IDC_BTN_START_CONNECT           1124
#define IDC_BUTTON2                     1125
#define IDC_BTN_STOP_COM                1125
#define IDC_BTN_START_COM               1126

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1127
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
